import { Flex, Heading } from "@chakra-ui/react";
import Head from "next/head";

const History = () => {
  return (
    <Flex direction="column" minH="100vh">
      <Head>
        <title>Yellowstone | History</title>
        <meta
          name="Project website for GEOL-201L at CSUF"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Heading>This is the history page</Heading>
    </Flex>
  );
};

export default History;
