import Head from "next/head";
import { Flex, Heading, Text } from "@chakra-ui/react";
import Banner from "../components/Home/Banner/Banner";
import Card from "../components/Home/Card";
import Row from "../components/Home/Row/Row";

export default function Home() {
  return (
    <Flex direction="column" w="100%">
      <Head>
        <title>Yellowstone | Home</title>
        <meta name="viewport" content="initial-scale=1.0, width=device-width" />
        <meta
          name="Project website for GEOL-201L at CSUF"
          content="Generated by create next app"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner />
      <Flex wrap={["wrap", "nowrap"]}>
        <Card imageSource="/img/buffalo.jpg">
          <Heading
            mt="4"
            as="h3"
            fontSize={["md", "xl"]}
            lineHeight="1.5"
            textTransform="uppercase"
            fontWeight="400"
            color="#d1d1d3"
          >
            Short Article
          </Heading>
          <Heading
            as="h2"
            fontSize={["2xl", "4xl"]}
            lineHeight="1.5"
            fontWeight="700"
          >
            Wildlife of Yellowstone
          </Heading>
          <Text
            mt="4"
            fontSize={["md", "lg"]}
            lineHeight="1.5"
            fontWeight="400"
            color="#d1d1d3"
          >
            Learn about the wildlife in the park.
          </Text>
        </Card>
        <Card imageSource="/img/erupt.jpg">
          <Heading
            mt="4"
            as="h3"
            fontSize={["md", "xl"]}
            lineHeight="1.5"
            textTransform="uppercase"
            fontWeight="400"
            color="#d1d1d3"
          >
            Park Essentials
          </Heading>
          <Heading
            as="h2"
            fontSize={["2xl", "4xl"]}
            lineHeight="1.5"
            fontWeight="700"
          >
            Geysers of Yellowstone
          </Heading>
          <Text
            mt="4"
            fontSize={["md", "lg"]}
            lineHeight="1.5"
            fontWeight="400"
            color="#d1d1d3"
          >
            Read up on how geysers formed in the park.
          </Text>
        </Card>
      </Flex>
      <Row
        rowHeight="300px"
        imageSource="/img/prismatic.jpg"
        contentPosition="right"
        caption="National Geographic"
        header="America's National Parks"
        buttonLink="https://youtu.be/7OMxBlK46wY"
        buttonText="Watch Now"
      />
      <Row
        rowHeight="480px"
        imageSource="/img/spring.jpg"
        contentPosition="center"
        caption="The Yellowstone Super Volcano"
        header="Yellowstone Caldera"
        buttonLink=""
        buttonText="Read Article"
      />
      <Row
        rowHeight="480px"
        imageSource="/img/prettylake.webp"
        contentPosition="center"
        caption="Park Biology"
        header="Flora &amp; Fauna"
        buttonLink=""
        buttonText="Learn more"
      />
      <Row
        rowHeight="300px"
        imageSource="/img/people.jpg"
        contentPosition="right"
        caption="History"
        header="Creation of the Park"
        buttonLink=""
        buttonText="Learn more"
      />
      <Flex wrap={["wrap", "nowrap"]}>
        <Card imageSource="/img/lake.jpg">
          <Heading
            mt="4"
            as="h3"
            fontSize={["md", "xl"]}
            lineHeight="1.5"
            textTransform="uppercase"
            fontWeight="400"
            color="#d1d1d3"
          >
            Park Essentials
          </Heading>
          <Heading
            as="h2"
            fontSize={["2xl", "4xl"]}
            lineHeight="1.5"
            fontWeight="700"
          >
            Earthquakes
          </Heading>
          <Text
            mt="4"
            fontSize={["md", "lg"]}
            lineHeight="1.5"
            fontWeight="400"
            color="#d1d1d3"
          >
            Earthquakes in the park, and what they mean.
          </Text>
        </Card>
        <Card imageSource="/img/natgeo.webp">
          <Heading
            mt="4"
            as="h3"
            fontSize={["md", "xl"]}
            lineHeight="1.5"
            textTransform="uppercase"
            fontWeight="400"
            color="#d1d1d3"
          >
            Park Essentials
          </Heading>
          <Heading
            as="h2"
            fontSize={["2xl", "4xl"]}
            lineHeight="1.5"
            fontWeight="700"
          >
            What is a National Park?
          </Heading>
          <Text
            mt="4"
            fontSize={["md", "lg"]}
            lineHeight="1.5"
            fontWeight="400"
            color="#d1d1d3"
          >
            Learn how to protect the geologic resources of a nature.
          </Text>
        </Card>
      </Flex>
      <Row
        rowHeight="480px"
        imageSource="/img/river.jpeg"
        contentPosition="right"
        caption="Yellowstone Essentials"
        header="Climate"
        buttonLink=""
        buttonText="Learn more"
      />
      <Row
        rowHeight="480px"
        imageSource="/img/essence.jpg"
        contentPosition="left"
        caption="Inspiration and References"
        header="About This Website"
        buttonLink=""
        buttonText="Learn more"
      />
    </Flex>
  );
}
