import { Heading, Text, Flex, Link, Box, Image } from "@chakra-ui/react";
import { Swiper, SwiperSlide } from "swiper/react";
import { Navigation, Pagination, A11y } from "swiper";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import "swiper/css/scrollbar";

const Summary = () => {
  return (
    <Flex direction="column" mb="8">
      <Heading mb="4">About this website</Heading>
      <Text mb="8">Howdy, Im Sean.</Text>
      <Text mb="8">
        During Fall semester of 2021, I created this website as a project for my
        Geology class GEOL-201l at CSU Fullerton. This class was a single unit
        class that consisted mostly of undergrad Computer Science students that
        needed science elective credits. Wayne Henderson, the very rad professor
        of our class, wanted to tie in Geology with Computer Science so he had
        the great idea of creating websites for our projects.
      </Text>
      <Text mb="8">
        My goal for this website was to create a professional looking blog-like
        site but for learning about Yellowstone National Park. Why Yellowstone?
        It was a topic that came up a bunch in my other Geology class. I was
        fascinated with the fact that Yellowstone is a super volcano that
        erupted thousands of years ago, with a blast radius so insane that ash
        rained over California.
      </Text>
      <Text mb="8">
        Sidebar: our class actually went on a field trip to the Nopah Mountain
        Range and got to see some of this ash by Shoshone. The crazy part about
        the ash was that people built houses into them during the Great
        Depression. You can see some of these pictures below.
      </Text>
      <Box>
        <Swiper
          modules={[Navigation, Pagination, A11y]}
          slidesPerView={1}
          navigation
          pagination={{ clickable: true }}
        >
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_111029.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_111711.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_111719.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_130524.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_130528.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_140327.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_155551.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_164837.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_165212.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_165904.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_173611.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_173956.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211002_181404.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_111705.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_112750.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_112855.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_120347.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_120351.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_120400.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_120712.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_120954.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_121025.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_121028.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_121128.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_121218.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
          <SwiperSlide>
            <Box>
              <Image
                alt="Spring"
                src="/img/field_trips/20211111_132646.jpg"
                objectFit="scale-down"
                w="100%"
                h="md"
              />
              <Text
                textAlign="center"
                fontSize="sm"
                color="gray.300"
                mb="8"
                mt="2"
              ></Text>
            </Box>
          </SwiperSlide>
        </Swiper>
      </Box>
      <Text>
        All of my references for my articles can be found below. Additionally,
        you can find the tech stack I used for this project. ALSO you can find
        the{" "}
        <Link href="https://github.com/slimsloth" color="blue.200" isExternal>
          link for the GitHub source code repository for this website here.
        </Link>{" "}
        I hope that you have learned something reading through this site,
        whether it be geology related or computer science related.
      </Text>
    </Flex>
  );
};

export default Summary;
